#!/usr/bin/env bash
# Setup script for Cloudflare Tunnel

echo "Setting up Cloudflare Tunnel for Home Assistant"
echo "================================================"
echo ""
echo "Option 1: Via Cloudflare Dashboard (Recommended)"
echo "-------------------------------------------------"
echo "1. Go to: https://one.dash.cloudflare.com/"
echo "2. Look for 'Networks' in the left sidebar"
echo "3. Click on 'Tunnels' under Networks"
echo "4. Create a new tunnel named 'husbuddies-tunnel'"
echo "5. Save the credentials JSON to /var/lib/cloudflared/husbuddies-tunnel.json"
echo ""
echo "Option 2: Via Command Line"
echo "---------------------------"
echo "Install cloudflared locally and run:"
echo ""
echo "  # Login to Cloudflare"
echo "  cloudflared tunnel login"
echo ""
echo "  # Create the tunnel"
echo "  cloudflared tunnel create husbuddies-tunnel"
echo ""
echo "  # This will output credentials JSON - save it to:"
echo "  # /var/lib/cloudflared/husbuddies-tunnel.json on ultraviolet"
echo ""
echo "  # Get the tunnel UUID from:"
echo "  cloudflared tunnel list"
echo ""
echo "  # Create DNS route"
echo "  cloudflared tunnel route dns husbuddies-tunnel home.husbuddies.gay"
echo ""
echo "After setting up the tunnel, run 'update' on ultraviolet to apply the configuration."